name: PowerShell Example

on: [push]

jobs:
  powershell-job:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Windows Commands
        run: |
          choco install nircmd -y
          nircmd savescreenshotfull test.jpg
          whoami
          net session

      - name: test persistance
        run: |
          dir $env:tmp
          echo hi > $env:tmp\blah.txt
          dir $env:tmp

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test.jpg
          git commit -m "Update test.jpg"
          git push
